version: '3.8'

services:
  httpd:
    build:
      context: ./.docker/httpd/build
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/html:ro'
      - './.docker/httpd/config/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro'
  php-fpm:
    build:
      context: ./.docker/php-fpm/build
    volumes:
      - '.:/var/www/html:ro'
