version: '3.8'

services:
  php-cli:
    build:
      context: ./.docker/php-cli/build
    volumes:
      - '.:/var/www/html:rw'
      - './.docker/php-fpm/config/z10-xdebug.ini:/usr/local/etc/php/conf.d/z10-xdebug.ini:ro'
