version: '3.8'

services:
  httpd:
    build:
      context: ./.docker/httpd/build
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/html:ro'
      - './.docker/httpd/config/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro'
  php-fpm:
    build:
      context: ./.docker/php-fpm/build
    volumes:
      - '.:/var/www/html:ro'
      - './.docker/php-fpm/config/z10-xdebug.ini:/usr/local/etc/php/conf.d/z10-xdebug.ini:ro'
      - './.xdebug-profiler:/var/www/html/.xdebug-profiler:rw'
      - './var:/var/www/html/var:rw'
